services:
  api-gateway:
    image: nginx
    container_name: api-gateway
    restart: on-failure
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    environment:
      - NGINX_PORT=8080

  rabbitmq:
    image: rabbitmq:4.3.0-management-alpine
    container_name: rabbitmq
    restart: on-failure
    environment:
      - 'RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management path_prefix "/queue"'

  accounts-service:
    build: 
      context: ./accounts
    container_name: accounts-service
    depends_on:
      accounts-db:
        condition: service_healthy
    environment:
      - PORT=8081
      - DATABASE_CONNECTION=postgres://user:pass@accounts-db:5432/accounts # dev only
      - RABBITMQ_CONNECTION=amqp://guest:guest@rabbitmq:5672 # dev only
    develop:
      watch:
        - action: rebuild
          path: ./accounts

  accounts-db:
    image: postgres:14.23-alpine
    container_name: accounts-db
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass # dev only
      - POSTGRES_DB=accounts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432"]
      interval: 3s
      timeout: 5s
      retries: 5

  fraud-service:
    build: 
      context: ./fraud
    container_name: fraud-service
    environment:
      - PORT=8081
    develop:
      watch:
        - action: rebuild
          path: ./fraud
