// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                int64
	BalanceInPennies  pgtype.Int8
	AccountHolderName string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}
