// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error
}

var _ Querier = (*Queries)(nil)
