// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (balance_in_pennies, account_holder_name)
VALUES ($1, $2)
RETURNING id, balance_in_pennies
`

type CreateAccountParams struct {
	BalanceInPennies  int64
	AccountHolderName string
}

type CreateAccountRow struct {
	ID               int64
	BalanceInPennies int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.BalanceInPennies, arg.AccountHolderName)
	var i CreateAccountRow
	err := row.Scan(&i.ID, &i.BalanceInPennies)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (description, account_id)
VALUES ($1, $2)
RETURNING id, status
`

type CreateTransactionParams struct {
	Description string
	AccountID   int64
}

type CreateTransactionRow struct {
	ID     int64
	Status TransactionStatus
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.Description, arg.AccountID)
	var i CreateTransactionRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const createTransactionLedgerEntry = `-- name: CreateTransactionLedgerEntry :one
INSERT INTO transactions_ledger (idempotency_key, is_compensating_txn, transaction_id, account_id, other_party_account_id, amount_in_pennies)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateTransactionLedgerEntryParams struct {
	IdempotencyKey      pgtype.UUID
	IsCompensatingTxn   bool
	TransactionID       int64
	AccountID           int64
	OtherPartyAccountID int64
	AmountInPennies     int64
}

func (q *Queries) CreateTransactionLedgerEntry(ctx context.Context, arg CreateTransactionLedgerEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTransactionLedgerEntry,
		arg.IdempotencyKey,
		arg.IsCompensatingTxn,
		arg.TransactionID,
		arg.AccountID,
		arg.OtherPartyAccountID,
		arg.AmountInPennies,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const duplicatePaymentCheck = `-- name: DuplicatePaymentCheck :one
SELECT id FROM transactions_ledger
WHERE account_id = $1 AND idempotency_key = $2
FOR UPDATE
`

type DuplicatePaymentCheckParams struct {
	AccountID      int64
	IdempotencyKey pgtype.UUID
}

func (q *Queries) DuplicatePaymentCheck(ctx context.Context, arg DuplicatePaymentCheckParams) (int64, error) {
	row := q.db.QueryRow(ctx, duplicatePaymentCheck, arg.AccountID, arg.IdempotencyKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, balance_in_pennies, account_holder_name, created_at, updated_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.BalanceInPennies,
		&i.AccountHolderName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, balance_in_pennies, account_holder_name, created_at, updated_at FROM accounts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.BalanceInPennies,
		&i.AccountHolderName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionLedgerEntries = `-- name: GetTransactionLedgerEntries :many
SELECT ledger.id, ledger.transaction_id, ledger.account_id, ledger.other_party_account_id, ledger.idempotency_key, ledger.is_compensating_txn, ledger.amount_in_pennies, ledger.created_at, 
  other_party.account_holder_name AS other_party_name,
  txn.status
FROM transactions_ledger ledger
INNER JOIN accounts other_party ON ledger.other_party_account_id = other_party.id
INNER JOIN transactions txn ON ledger.transaction_id = txn.id
WHERE ledger.account_id = $1
ORDER BY ledger.created_at DESC
`

type GetTransactionLedgerEntriesRow struct {
	ID                  int64
	TransactionID       int64
	AccountID           int64
	OtherPartyAccountID int64
	IdempotencyKey      pgtype.UUID
	IsCompensatingTxn   bool
	AmountInPennies     int64
	CreatedAt           pgtype.Timestamptz
	OtherPartyName      string
	Status              TransactionStatus
}

func (q *Queries) GetTransactionLedgerEntries(ctx context.Context, accountID int64) ([]GetTransactionLedgerEntriesRow, error) {
	rows, err := q.db.Query(ctx, getTransactionLedgerEntries, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionLedgerEntriesRow
	for rows.Next() {
		var i GetTransactionLedgerEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.OtherPartyAccountID,
			&i.IdempotencyKey,
			&i.IsCompensatingTxn,
			&i.AmountInPennies,
			&i.CreatedAt,
			&i.OtherPartyName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE accounts
SET balance_in_pennies = $2
WHERE id = $1
`

type UpdateBalanceParams struct {
	ID               int64
	BalanceInPennies int64
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance, arg.ID, arg.BalanceInPennies)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions
SET status = $2
WHERE id = $1
`

type UpdateTransactionParams struct {
	ID     int64
	Status TransactionStatus
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.Exec(ctx, updateTransaction, arg.ID, arg.Status)
	return err
}
