// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (balance_in_pennies, account_holder_name)
VALUES ($1, $2)
RETURNING id, balance_in_pennies
`

type CreateAccountParams struct {
	BalanceInPennies  int64
	AccountHolderName string
}

type CreateAccountRow struct {
	ID               int64
	BalanceInPennies int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.BalanceInPennies, arg.AccountHolderName)
	var i CreateAccountRow
	err := row.Scan(&i.ID, &i.BalanceInPennies)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, balance_in_pennies, account_holder_name, created_at, updated_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.BalanceInPennies,
		&i.AccountHolderName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, balance_in_pennies, account_holder_name, created_at, updated_at FROM accounts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.BalanceInPennies,
		&i.AccountHolderName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE accounts
SET balance_in_pennies = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateBalanceParams struct {
	ID               int64
	BalanceInPennies int64
	UpdatedAt        pgtype.Timestamp
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance, arg.ID, arg.BalanceInPennies, arg.UpdatedAt)
	return err
}
