// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (balance_in_pennies, account_holder_name)
VALUES ($1, $2)
RETURNING id, balance_in_pennies
`

type CreateAccountParams struct {
	BalanceInPennies  int64
	AccountHolderName string
}

type CreateAccountRow struct {
	ID               int64
	BalanceInPennies int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.BalanceInPennies, arg.AccountHolderName)
	var i CreateAccountRow
	err := row.Scan(&i.ID, &i.BalanceInPennies)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (description, account_id)
VALUES ($1, $2)
RETURNING id, status
`

type CreateTransactionParams struct {
	Description string
	AccountID   int64
}

type CreateTransactionRow struct {
	ID     int64
	Status TransactionStatus
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.Description, arg.AccountID)
	var i CreateTransactionRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const createTransactionLedgerEntry = `-- name: CreateTransactionLedgerEntry :one
INSERT INTO transactions_ledger (transaction_id, account_id, other_party_account_id, amount_in_pennies)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateTransactionLedgerEntryParams struct {
	TransactionID       int64
	AccountID           int64
	OtherPartyAccountID int64
	AmountInPennies     int64
}

func (q *Queries) CreateTransactionLedgerEntry(ctx context.Context, arg CreateTransactionLedgerEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTransactionLedgerEntry,
		arg.TransactionID,
		arg.AccountID,
		arg.OtherPartyAccountID,
		arg.AmountInPennies,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, balance_in_pennies, account_holder_name, created_at, updated_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.BalanceInPennies,
		&i.AccountHolderName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, balance_in_pennies, account_holder_name, created_at, updated_at FROM accounts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.BalanceInPennies,
		&i.AccountHolderName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE accounts
SET balance_in_pennies = $2
WHERE id = $1
`

type UpdateBalanceParams struct {
	ID               int64
	BalanceInPennies int64
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance, arg.ID, arg.BalanceInPennies)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions
SET status = $2
WHERE id = $1
`

type UpdateTransactionParams struct {
	ID     int64
	Status TransactionStatus
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.Exec(ctx, updateTransaction, arg.ID, arg.Status)
	return err
}
