// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FraudCheck struct {
	ID            int64
	TransactionID int64
	RiskScore     int16
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
