// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"
)

const createFraudCheck = `-- name: CreateFraudCheck :one
INSERT INTO fraud_checks (transaction_id, risk_score)
VALUES ($1, $2)
RETURNING id
`

type CreateFraudCheckParams struct {
	TransactionID int64
	RiskScore     int16
}

func (q *Queries) CreateFraudCheck(ctx context.Context, arg CreateFraudCheckParams) (int64, error) {
	row := q.db.QueryRow(ctx, createFraudCheck, arg.TransactionID, arg.RiskScore)
	var id int64
	err := row.Scan(&id)
	return id, err
}
